version: '3'

services:
  latest:
    
    # For build image
    # build: .
    # image: myimage-for-jupyterlab

    # For pull image
    image: epaniuqs/myimage-for-jupyterlab

    container_name: myimage-for-jupyterlab
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8888:8888
    volumes:
      - ./:/home/
    tty: true
